name: Build LaTeX document
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: anthony.liot.tex

      - name: Generate Git Tag
        id: generate_tag
        run: |
          VERSION_PREFIX="v"
          VERSION_INCR=$(git rev-list --count HEAD | head -n 1)
          VERSION_TIME=$(date +'%Y%m%d' | head -n 1)
          VERSION_SHA=$(git rev-parse HEAD | cut -c 1-8  | head -n 1)
          VERSION_TAG="${VERSION_PREFIX}${VERSION_INCR}.${VERSION_TIME}.${VERSION_SHA}"
          echo "Generated new tag: $VERSION_TAG"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
  
      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag $VERSION_TAG || true
          git push origin $VERSION_TAG || true
          git fetch || true
            
      - name: Upload PDF file to artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: anthony.liot.pdf

      - name: Upload PDF file to tag
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: anthony.liot.pdf
          asset_name: anthony.liot.pdf
          tag: $VERSION_TAG
          overwrite: true
          body: "Resume $VERSION_TAG"